# Vagrant.configure("2") do |config|
#   # Box compatible con Hyper-V
#   config.vm.box = "generic/ubuntu2204"

#   # Configuración de red para Hyper-V (elige el switch en el primer 'vagrant up')
#   config.vm.network "public_network"

# Usar el script externo para instalar Docker y Kubernetes
#  config.vm.provision "shell", path: "scripts/instalar_docker_k8s.sh"


#   # Provisionamiento con Shell
#   config.vm.provision "shell", inline: <<-SHELL
#     echo "¡Hola desde el provisionamiento!" > /tmp/hola.txt
#     apt update -y && apt install -y nginx
#     systemctl enable nginx
#     systemctl start nginx
#   SHELL
# end

###################################################################

Vagrant.configure("2") do |config|
  # Box compatible con Hyper-V
  config.vm.box = "generic/ubuntu2204"

  # Red privada (puedes cambiar la IP si la necesitas distinta)
  config.vm.network "private_network", ip: "192.168.33.20"

  # Montar carpeta local en la VM
  config.vm.synced_folder "./proyect-prueba-deploy", "/var/www/html", type: "rsync"

  config.vm.provision "shell", inline: <<-SHELL
    apt update && apt install -y nginx
    systemctl enable --now nginx
SHELL

end
###################################################
# Vagrant.configure("2") do |config|
#   config.vm.box = "generic/ubuntu2204"

#   config.vm.provider "hyperv" do |h|
#     h.memory = 2048
#     h.cpus = 2
#   end

#   # Forwarding para acceso web
#   config.vm.network "forwarded_port", guest: 80, host: 8080

#   # Montar carpeta local en la VM
#   config.vm.synced_folder "./mi_proyecto_web", "/var/www/html", owner: "www-data", group: "www-data"

#   config.vm.provision "shell", inline: <<-SHELL
#     apt update && apt install -y nginx
#     systemctl enable --now nginx
#   SHELL
# end
